### ISSUE TITLE
Idle Eth Dispatch: hang on R chip `TestWrapCompletionQOnInsufficientSpace`

### ISSUE THREAD

**Issue by aliuTT** [tenstorrent-metal/tt-metal#6374] opened 2024-03-13 20:40 UTC
- `git checkout ucheema/fd-on-idle-erisc`
- `WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml TT_METAL_ENABLE_REMOTE_CHIP=1 ./build/test
/tt_metal/unit_tests_fast_dispatch --gtest_filter="CommandQueueSingleCardFixture.TestWrapCompletionQOnInsufficientSpace"`
OR
- `WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml TT_METAL_ENABLE_REMOTE_CHIP=1 ./build/test
/tt_metal/unit_tests_fast_dispatch --gtest_filter="CommandQueueSingleCardFixture.TestWrapCompletionQOnInsufficientSpace2"`

Seeing it pass on L chip, but hanging on R chip.

**Comment by ubcheema** [comment] 2024-03-13 20:53
do these parameters need to be adjusted?

        ```
std::vector<uint32_t> remote_pull_and_push_compile_args = {
            0, // host_issue_queue_read_ptr_addr,
            0, // issue_queue_start_addr,
            0, // issue_queue_size,
            0, // host_completion_queue_write_ptr_addr,
            0, // completion_queue_start_addr,
            0, // completion_queue_size,
            0, // host_finish_addr
            cmd_start_tensix,
            data_section_addr_tensix,
            producer_data_buffer_size_tensix,
            cmd_start_tensix,
            consumer_data_buffer_size_tensix,
            (uint32_t)tt::PullAndPushConfig::REMOTE_PULL_AND_PUSH
        };
```

for mmio case, I have this;
                ```
uint32_t cmd_start_producer = eth_core ? cmd_start_eth_dispatch : cmd_start_tensix;
                uint32_t data_section_addr_producer = eth_core ? get_data_section_l1_address(true, true) : data_section_addr_tensix;
                uint32_t producer_data_buffer_size = eth_core ? get_cq_data_buffer_size(true, true) : producer_data_buffer_size_tensix;
```

**Comment by ubcheema** [comment] 2024-03-13 20:55
at least buffer size is different when fd is running on Tensix Vs ethernet cores.

**Comment by ubcheema** [comment] 2024-03-15 16:54
Hang can be reproduced on main by moving L1 unreserved base from 120 KB to 119 KB. 
It is not related to FD on ethernet cores feature. But is exposed because we have to move the l1 unreserved base lower to have more memory on ethernet cores for CBs.

**Comment by DrJessop** [comment] 2024-03-15 19:04
Investigating.

**Comment by DrJessop** [comment] 2024-03-18 16:35
FYI, on main, both TestWrapCompletionQOnInsufficientSpace and TestWrapCompletionQOnInsufficientSpace2 pass with watcher enabled on tensix. Please rebase and see what happens on your branch.

**Comment by DrJessop** [comment] 2024-03-19 20:21
I checked in fixes to main. Can you confirm whether or not this resolves the issue so that we can close?

**Comment by ubcheema** [comment] 2024-03-19 21:46
Verified that it works on R chip.
Thanks for the fix.

**Closed by ubcheema** 2024-03-19 21:46 UTC
Labels: bug, P1_critical
