### ISSUE TITLE
Program cache does not work with multi-device

### ISSUE THREAD

**Issue by uaydonat** [tenstorrent-metal/tt-metal#6295] opened 2024-03-12 15:58 UTC
These are the LLM demos that currently has program cache disabled because it does not work on multi-chip: llama2, falcon40b, mixtral.

fyi @cglagovichTT @yieldthought @TT-BrianLiu

**Comment by jliangTT** [comment] 2024-03-12 20:29
Some multi-device program cache work has been done here: https://github.com/tenstorrent-metal/tt-metal/issues/6031 

What is different about this ask?

**Comment by jliangTT** [comment] 2024-03-12 20:29
triaging to tt-nn board to also have more knowledgeable folks comment.

**Comment by TT-BrianLiu** [comment] 2024-03-12 20:42
The difference is, before we thought program caching for multi-chip was not implemented, but turns out it is. So that means program caching is exposing some other bug in runtime. For example, with program caching everything is faster so there could be some race.

**Comment by arakhmati** [comment] 2024-03-13 15:09
Are there tests for multi-device program cache?

**Comment by TT-BrianLiu** [comment] 2024-03-13 15:19
> Are there tests for multi-device program cache?

There are, but these are all model level tests. Likely, it's not a direct issue with program cache, but rather program cache is exposing some other issues. My guess is it's difficult to reproduce in unit tests

**Comment by tt-asaigal** [comment] 2024-03-13 15:28
Hey @TT-BrianLiu we should try reproducing this with basic unit tests. We can start with the multichip tests we have and if we don't see a hang there, we can try trimming any LLM to make debug easier.

**Comment by jliangTT** [comment] 2024-03-13 15:59
Clarifying the next step: 

- multi-device program cache is implementation complete but there are bugs (pcc or/and hang)
- @cglagovich is observing this bug and is providing a repro 
- @tt-asaigal will lead the debug on the runtime side and work with @TT-BrianLiu if this issue emerges to an op, @arakhmati if it is more a ttnn infra.

**Comment by cglagovich** [comment] 2024-03-13 17:24
Tracking Llama hang here https://github.com/tenstorrent-metal/tt-metal/issues/6360

**Comment by jliangTT** [comment] 2024-03-15 21:41
@aliuTT can this be closed?

**Comment by aliuTT** [comment] 2024-03-15 21:44
I think so

**Comment by jliangTT** [comment] 2024-03-15 21:53
ok. closing. @cglagovich @uaydonat , re-open if you don't agree.

**Closed by jliangTT** 2024-03-15 21:53 UTC
Labels: bug, P0_Showstopper, LLM_bug
