### ISSUE TITLE
Layernorm produces low PCC for WIDTH Sharding

### ISSUE THREAD

**Issue by johanna-rock-tt** [tenstorrent-metal/tt-metal#6731] opened 2024-03-25 11:38 UTC
**Describe the bug**
When using layernorm with WIDTH sharded input it produces low PCC (PCC=0.61 for seq length 128).

**To Reproduce**
1. Checkout `jrock/prefill-functional@df16bb73cc381f19eac650a4a0840334ccecb2b7`
2. Run unit test `pytest models/experimental/falcon40b/tests/ops/test_falcon_layernorm.py::test_FalconLayernorm_inference`

**Additional Context**
This works for block sharded inputs (PCC=0.99), see commented options in the unit test for details.

**Comment by johanna-rock-tt** [comment] 2024-03-25 11:39
FYI @jliangTT @miacim  @cglagovich @xuncaiTT @kevinmiTT11

**Comment by jliangTT** [comment] 2024-03-25 15:42
@johanna-rock-tt , please help use the "op_cat: fused" for layernorm, and softmax type of operators support

**Comment by yugaoTT** [comment] 2024-03-28 17:56
the problem is in the order of fetching data from other worker cores. I fixed that and now running CI

**Comment by yugaoTT** [comment] 2024-03-28 18:38
merged, I'll close

**Closed by yugaoTT** 2024-03-28 18:38 UTC
Labels: bug, P1_critical, falcon_40b, op_cat: fused, LLM_bug, LLMs on Metal
