### ISSUE TITLE
An issue about the offset feature of get_noc_addr

### ISSUE THREAD

**Issue by sangwon-chae** [tenstorrent-metal/tt-metal#6053] opened 2024-03-06 01:52 UTC
We have a question about the offset feature of get_noc_addr. We're trying to implement a function to read data from a tensor starting at a desired position using the offset. However, in some cases, the offset seems to work fine, while in others, it behaves strangely. So, we investigated when the offset works correctly, and it seems to work properly only when the offset is a multiple of 32. Could you provide some guidance on this? It is required for LLM training. 

Our team's engineer(@hschoi4448) conducted tests as follows:
He used a tensor containing integers(uint32) from 0 to N as below.
For testing purposes, he implemented DPRINT as below, and in normal cases, the numbers come out in order.
However, if the offset is not a multiple of 32, strange values appear.
(The test content is within a thread.) 

Here is the code.

```
// reader data movement kernel code
        cb_reserve_back(cb_in0, 1);
        uint32_t l1_write_addr = get_write_ptr(cb_in0);
        id = 0;
        offset = 8 * 4;
        uint64_t src_noc_addr = get_noc_addr(id, s0, offset);
        noc_async_read(src_noc_addr, l1_write_addr, stick_size);
        noc_async_read_barrier();
        cb_push_back(cb_in0, 1);

            volatile tt_l1_ptr uint32_t* index_l1_ptr = reinterpret_cast<volatile tt_l1_ptr uint32_t*>(l1_write_addr);

            for (uint32_t x = 0 ;x < debug_print_size; x ++) {
                DPRINT << "Input index_l1_ptr[" << x << "] = " << index_l1_ptr[x] << "\n";
            }

// case1. offset = 1 * 4(sizeof uint32_t)
-> In this case, the offset doesn't seem to have any effect.
// expected result
Input index_l1_ptr[0] = 1
Input index_l1_ptr[1] = 2
Input index_l1_ptr[2] = 3
Input index_l1_ptr[3] = 4
Input index_l1_ptr[4] = 5
Input index_l1_ptr[5] = 6
Input index_l1_ptr[6] = 7
Input index_l1_ptr[7] = 8
Input index_l1_ptr[8] = 9
// real
Input index_l1_ptr[0] = 0
Input index_l1_ptr[1] = 1
Input index_l1_ptr[2] = 2
Input index_l1_ptr[3] = 3
Input index_l1_ptr[4] = 4
Input index_l1_ptr[5] = 5
Input index_l1_ptr[6] = 6
Input index_l1_ptr[7] = 7
Input index_l1_ptr[8] = 8

// case2. offset = 4 * 4
For some unknown reason, it outputs zero.
// expected result
Input index_l1_ptr[0] = 4
Input index_l1_ptr[1] = 5
Input index_l1_ptr[2] = 6
Input index_l1_ptr[3] = 7
Input index_l1_ptr[4] = 8
Input index_l1_ptr[5] = 9
Input index_l1_ptr[6] = 10
Input index_l1_ptr[7] = 11
Input index_l1_ptr[8] = 12

// real 
Input index_l1_ptr[0] = 0
Input index_l1_ptr[1] = 0
Input index_l1_ptr[2] = 0
Input index_l1_ptr[3] = 0
Input index_l1_ptr[4] = 4
Input index_l1_ptr[5] = 5
Input index_l1_ptr[6] = 6
Input index_l1_ptr[7] = 7
Input index_l1_ptr[8] = 8

// case3. offset = 8 * 4
The offset works as expected when it's a multiple of 32.
// expected result
Input index_l1_ptr[0] = 8
Input index_l1_ptr[1] = 9
Input index_l1_ptr[2] = 10
Input index_l1_ptr[3] = 11
Input index_l1_ptr[4] = 12
Input index_l1_ptr[5] = 13
Input index_l1_ptr[6] = 14
Input index_l1_ptr[7] = 15
Input index_l1_ptr[8] = 16

// real
Input index_l1_ptr[0] = 8
Input index_l1_ptr[1] = 9
Input index_l1_ptr[2] = 10
Input index_l1_ptr[3] = 11
Input index_l1_ptr[4] = 12
Input index_l1_ptr[5] = 13
Input index_l1_ptr[6] = 14
Input index_l1_ptr[7] = 15
Input index_l1_ptr[8] = 16

**Comment by TT-BrianLiu** [comment] 2024-03-06 16:35
Take a look at: `tt_metal/hw/inc/dataflow_api.h`. We have many implementations for `get_noc_addr`:
- The most basic one is this, which just returns you the noc addr without offset. I think you should try using this one and add the offset by yourself.
![image](https://github.com/tenstorrent-metal/tt-metal/assets/109366241/0f3bf8d1-bd13-4b8b-a851-97893d8e50cb)
- The one you are using seems to be one of this. It is templated on a specific InterleavedAccessor and is implemented by the accessor structs. The offsets exposed here might be specific to certain banking strategies so might not be generic. 
![image](https://github.com/tenstorrent-metal/tt-metal/assets/109366241/9e069a4e-593b-4d83-979f-eb0799615cc6)

**Comment by sangwon-chae** [comment] 2024-03-06 23:56
@TT-BrianLiu We will take a look, and get back to you. Thanks!

**Comment by jliangTT** [comment] 2024-03-08 21:32
closing this and re-open if needed.

**Comment by sangwon-chae** [comment] 2024-03-11 23:21
@jliangTT 
We've tried the two methods you provided, but we still have the same issue where the offset needs to be a multiple of 32 when using Addrgen.

First method:
`std::uint64_t get_noc_addr(std::uint32_t addr) {
    /*
        Get an encoding which contains the address in L1 on the current core that you want to
        read from/write to via the noc
    */`
We looked at the code you are using, and it seems that the addr value needs to be an index of a circular buffer.
However, the input value you are providing is a DRAM address, which cannot be used with a circular buffer.


Second method:
`FORCE_INLINE
std::uint64_t get_noc_addr(std::uint32_t noc_x, std::uint32_t noc_y, std::uint32_t addr) {
    /*
        Get an encoding which contains tensix core and address you want to
        write to via the noc multicast
    */

    return NOC_XY_ADDR(NOC_X(noc_x), NOC_Y(noc_y), addr);
}

uint32_t offset = 8 * 4;
uint32_t noc_x = 0;
uint32_t noc_y = 0;
index_noc_addr = get_noc_addr(noc_x, noc_y, dram_addr) + offset;`
We also tested the second method of directly adding the offset.
However, it only works when the offset is a multiple of 32, just like when using Addrgen.

**Comment by jliangTT** [comment] 2024-03-27 14:41
i am putting this on p1 for now and we can discuss to raise this to p0 at today's meeting

**Comment by jliangTT** [comment] 2024-03-27 14:55
@TT-BrianLiu do we have code example that show non-multiple-of-32 case? 

@sangwon-chae, can you make a small repro to show your code and check in? (in the past i have seen it is so much faster for developers to jump right in and investigate) c.c. @razorback3

**Comment by TT-BrianLiu** [comment] 2024-03-27 16:10
Can we hop on a call and figure out what we are trying to do? Some questions:
- How are your tensors stored?
- What are you trying to do reading the data in CB as volatile ptrs?

**Comment by hschoi4448** [comment] 2024-03-28 00:19
I have created a branch for reproducing the issue.
- https://github.com/tenstorrent-metal/tt-metal/tree/hyungsuk/get_noc_addr_bug_test

Running the `pytest ./tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_getitem.py` command should display the output from `DPRINT`.

The test kernel code is located at the following path.
https://github.com/tenstorrent-metal/tt-metal/blob/hyungsuk/get_noc_addr_bug_test/tt_eager/tt_dnn/op_library/moreh_getitem/moreh_getitem_rm/kernels/reader_moreh_getitem.cpp#L105

**Comment by jliangTT** [comment] 2024-04-03 23:22
there is a constraint/limitation that the read to DRAM has to be mulitple of 32 - if you enable watcher this will issue an error

**Closed** 2024-04-03 23:23 UTC
Labels: bug, moreh, P1_critical, todo
