### ISSUE TITLE
Hang in pre-tilize in conv compute kernel when in0 is BFLOAT8_B and in1 is BFLOAT16

### ISSUE THREAD

**Issue by TT-BrianLiu** [tenstorrent-metal/tt-metal#4280] opened 2023-12-12 01:30 UTC
In `tt_eager/tt_dnn/op_library/conv/kernels/conv_bmm_tilize_col_major_out_blocks.cpp`, line 169 should work but hangs if `in1_cb` is BFLOAT16 and the in0 for matmul (here, `tilized_in0_cb_id`) is BFLOAT8_B. `in0_pretilize_cb_id` is ROW_MAJOR and always BFLOAT16, so I don't think we even need sraA reconfig in this case? 

<img width="828" alt="image" src="https://github.com/tenstorrent-metal/tt-metal/assets/109366241/74f048b7-004b-4ef3-a3d8-45dcdef43ece">

To get the test to pass, you can force the reconfig to happen with: `unpack_reconfig_data_format_srca(in1_cb_id);`

For reference, there are other convs where we don't have the pre-tilize block and instead tilize once we get input from reader. The dataformats in the llk APIs should be the same here, but we don't need to force the reconfig.

<img width="694" alt="image" src="https://github.com/tenstorrent-metal/tt-metal/assets/109366241/f2ec6a6f-2715-4a80-aa11-3bbf5a61fd83">

Branch: `bliu/issue-4280`

Test: 
```
pytest models/demos/resnet/tests/test_resnet50_untilize_with_halo_and_conv_v2.py::test_resnet50_conv -k HiFi4-activations_BFLOAT8_B-weights_BFLOAT16-512-512-7-7-3-3-1-1-1-1-batch_8
```

**Comment by davorchap** [comment] 2024-01-24 18:30
@TT-BrianLiu is this still relevant?

**Comment by TT-BrianLiu** [comment] 2024-01-26 19:02
> @TT-BrianLiu is this still relevant?

I think so. Definitely something fishy going on when we switch between tilize and matmul. @tt-aho saw something similar when uplifting attention matmul to support mixed precision. He had to force the `srca` reconfig when it wasn't needed / shouldn't be doing anything.

**Comment by rtawfik01** [comment] 2024-02-21 21:54
I have a fix here:` rtawfik/issue_4280`
The issue is the `tilize_uninit` call reprograms the unpack config back to what was stored before tilize was executed. In this case, the default operand passed to tilize uninit is 0, when in reality it should have reverted back to the config of operand 1. I passed in the correct operand to the tilize uninit function so the test can pass. Ill debug the rest of these cases as well and try to make that operand not take in a default

**Comment by rtawfik01** [comment] 2024-02-22 22:38
Merged fix here: https://github.com/tenstorrent-metal/tt-metal/pull/5536

**Closed by rtawfik01** 2024-02-22 22:38 UTC
Labels: ResNet-50, LLK
