### ISSUE TITLE
EnqueueWriteBuffer functional: hitting assert buffer page size > 64K

### ISSUE THREAD

**Issue by aliuTT** [tenstorrent-metal/tt-metal#7264] opened 2024-04-09 20:09 UTC
```
     Verif | INFO     | Created a random vector of size 32768
                   Test | ERROR    | Test failed with exception!
terminate called after throwing an instance of 'std::runtime_error'
                   Test | ERROR    | TT_ASSERT @ tt_metal/impl/dispatch/command_queue.cpp:1450: int32_t(MAX_PREFETCH_COMMAND_SIZE) - int32_t(sizeof(CQPrefetchCmd) + sizeof(CQDispatchCmd)) >= padded_page_size
  what():  TT_ASSERT @ tt_metal/impl/dispatch/command_queue.cpp:1450: int32_t(MAX_PREFETCH_COMMAND_SIZE) - int32_t(sizeof(CQPrefetchCmd) + sizeof(CQDispatchCmd)) >= padded_page_size
backtrace:
 --- /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/build/lib/libtt_metal.so(+0x2e5614) [0x7f145ed7b614]
 --- tt::tt_metal::HWCommandQueue::enqueue_write_buffer(std::variant<std::reference_wrapper<tt::tt_metal::Buffer>, std::shared_ptr<tt::tt_metal::Buffer const> >, std::variant<std::shared_ptr<std::vector<unsigned short, std::allocator<unsigned short> > > const, std::shared_ptr<std::vector<unsigned int, std::allocator<unsigned int> > > const, std::shared_ptr<std::vector<float, std::allocator<float> > > const, std::shared_ptr<std::vector<bfloat16, std::allocator<bfloat16> > > const, void const*>, bool)
 --- /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/build/lib/libtt_metal.so(+0x2e685e) [0x7f145ed7c85e]
```

from https://github.com/tenstorrent-metal/tt-metal/actions/runs/8621138760/job/23629674281

**Comment by abhullar-tt** [comment] 2024-04-10 02:29
These are failing because a single buffer page is larger than 64K and we don't currently support writing partial buffer pages

**Comment by abhullar-tt** [comment] 2024-04-10 18:06
Moving this to P1 because this is hitting a known limitation that is being worked on

**Comment by tt-dma** [comment] 2024-04-10 20:52
`CommonFixture.Flatten` also hitting this assert, please re-enable when it's fixed

**Comment by davorchap** [comment] 2024-04-11 21:32
duplicate of #7380

**Closed by davorchap** 2024-04-11 21:32 UTC
Labels: P1_critical
