### ISSUE TITLE
Falcon40b prefill 4 chip hang with 60 layers 

### ISSUE THREAD

**Issue by s-jovic** [tenstorrent-metal/tt-metal#6289] opened 2024-03-12 14:00 UTC
[This commit](https://github.com/tenstorrent-metal/tt-metal/commit/69a2581ba8a9efc26b4c9c0f427ae5a348731135) (or the previous one, seems they have been merged together) broke the prefill. [Commit before that](https://github.com/tenstorrent-metal/tt-metal/commit/7d52e5b1f4bc8d7fde5b7fe8497907d8b0fd9a75) runs 60 layers without issues.

A couple of layers run normally. Frequency is at 800mhz

To reproduce you can run on main:

`pytest models/demos/falcon40b/tests/test_falcon_end_to_end.py -k "prefill and layers_60 and  BFLOAT8" --timeout 1000`

However, you would need to have all Falcon40b weights downloaded and prepared and this takes awhile, so we can also sync offline to see how to debug this together since I have the machine set up.

cc @johanna-rock-tt

**Comment by s-jovic** [comment] 2024-03-12 14:36
Decode seems to be affected as well, since demo works on the previous commit, and on the mentioned one it hangs after 7 tokens in my example:

`pytest --disable-warnings -q -s --input-method=cli --cli-input="Tell me a joke"  models/demos/falcon40b/demo/demo.py `

cc @skhorasganiTT

**Comment by SeanNijjar** [comment] 2024-03-12 14:49
Hey @s-jovic - I'm taking a look at this. I should have had this test case running already in my test_all_gather test list so I'll have to see why the cases marked as belonging to falcon40B didn't include the ones in the actual model (or if so, why it wasn't run).

I'm taking a look at this now. Is there a way to keep the weights cached locally or download them separately? I have a dedicated t3000. It has 128GB of ram - will that be enough?

**Comment by SeanNijjar** [comment] 2024-03-12 15:52
Based on discussion with @s-jovic, and the error behaviour (i.e. single layer doesn't hang but full model does and also that  we can make several passes through the model and generate 7 tokens before hanging), it seems like this is a non-deterministic hang.

Before I was able to merge the hanging commit, there were runtime issues that fundamentally prevented this new all-gather implementation from working: the new all-gather is implemented with a mix of worker and eth cores and that was fundamentally unsupported. My suspicion is there is another subtle bug here that might be causing the hang. 

For example, this issue may be one example: https://github.com/tenstorrent-metal/tt-metal/issues/6245

FYI @aliuTT

**Comment by SeanNijjar** [comment] 2024-03-12 17:48
Interesting behaviour - I've been able to reproduce the hang on an all_gather config in test_all_gather if I run the test in a tight loop:

```
    for i in range(1000):
        tt_out_tensors = None
        if i == 0:
            tt_out_tensors = ttl.tensor.all_gather(tt_input_tensors, dim, num_links, output_mem_config=mem_config)
        else:
            __ = ttl.tensor.all_gather(tt_input_tensors, dim, num_links, output_mem_config=mem_config)
        for d in devices:
            ttl.device.Synchronize(d)
```

I'm always able to pass the first (many) loop iterations but it _reliably_ hangs after the 64th iteration/call. So it is in fact deterministic, but not within the lifetime of an all-gather op invocation.

**Comment by aliuTT** [comment] 2024-03-12 17:50
That sounds like some data corruption somewhere after some max buffer size is hit. Not sure what though

**Comment by SeanNijjar** [comment] 2024-03-12 17:51
Yes! 64 is a suspicious number.

**Comment by aliuTT** [comment] 2024-03-12 18:16
Also, in general if we suspect an ND issue, let's say after 16 layers some test always hangs, it's always worthwhile to loop 1 layer many many times to see if it's ND on 1 layer, that is exposed since running 16 layers is basically testing that.

**Comment by SeanNijjar** [comment] 2024-03-12 18:18
Different configs hang at different fixed iteration counts (a bfloat8_b - fp16 doesn't ever have this issue):

`(4, 2, [4, 1, 256, 32], 0, ttl.tensor.Layout.TILE),       ## 128 iters before hang`
`(4, 2, [8, 5, 32, 384], 3, ttl.tensor.Layout.TILE),      # 64 iters before hang`
`(4, 2, [1, 1, 32, 16384], 3, ttl.tensor.Layout.TILE),     ## 64 iters before hang`
`(4, 2, [8, 5, 64, 384], 3, ttl.tensor.Layout.TILE),       # No hang `
`(4, 2, [8, 8, 256, 384], 1, ttl.tensor.Layout.TILE),     # No hang`

# Notes:
- No hang reproduced for fp16
- No hang reproduced for 8 chip, 1 link configs
- No hang reproduced for 4 chip, 1 link config

**Comment by SeanNijjar** [comment] 2024-03-12 18:18
Therefore @s-jovic, as an easier workaround - I recommend going to single link for the time being.

**Comment by SeanNijjar** [comment] 2024-03-12 20:44
Hey @aliuTT, I was seeing the following watcher error when running  a hanging config with watcher enabled:

```
                 Always | INFO     | While running kernels:
                 Always | INFO     |  brisc : tt_metal/impl/dispatch/kernels/cq_dispatcher.cpp
                 Always | INFO     |  ncrisc: blank
                 Always | INFO     |  triscs: blank
                 Always | WARNING  | Watcher stopped the device due to bad NOC L1/reg address
                 Always | INFO     | Last waypoint: NWPW,W,W,W,W 
                 Always | FATAL    | On core (x=1,y=10): brisc using noc0 reading L1[addr=0x0016e000,len=2048]
```

I've created a branch `snijjar/issue-6289`  where the issue is reproducible. It's based off main with a small test file tweak. You can reproduce the hang with (on t3000).:

- `export TT_METAL_WATCHER=40`
- `pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_all_gather.py -k "post_commit and mem_config0-input_dtype1-4-2-input_shape6-1-layout6"`

You should see it hanging deterministically. I'm going to pass this off to you since I have not seen this message for passing cases.

**Comment by aliuTT** [comment] 2024-03-13 03:41
Fixed issue on your branch: `655194575`

**Comment by aliuTT** [comment] 2024-03-13 03:42
I might go try 8 chip with program cache, this might fix a bunch of things

**Comment by aliuTT** [comment] 2024-03-13 04:36
@s-jovic Can you verify with this fix? And see if it fixes your issue? I was able to try Falcon40b decode on 4 chips with program cache, it was passing.

**Comment by s-jovic** [comment] 2024-03-13 09:13
Verified - both the decode demo and prefill 60 layers pass on this branch!

**Comment by aliuTT** [comment] 2024-03-13 16:44
Great, I'll close the issue then. The commit is in main now.

**Closed by aliuTT** 2024-03-13 16:44 UTC
Labels: bug, P1_critical, falcon_40b, op_cat: all gather
