### ISSUE TITLE
[Bug Report] Matmul 1D hang with l1 acc enabled

### ISSUE THREAD

**Issue by s-jovic** [tenstorrent-metal/tt-metal#6917] opened 2024-03-29 17:33 UTC
**Describe the bug**
Matmul 1D hangs if l1 acc is enabled.

**To Reproduce**
```
def test_reproduce_l1_acc_hang(device):
    M = 64
    K = 142
    N = 508

    a_shape = [1, 1, M * 32, K * 32]
    b_slice_shape = [1, 1, K * 32, N * 32]

    mem_config = ttl.tensor.MemoryConfig(ttl.tensor.TensorMemoryLayout.INTERLEAVED, ttl.tensor.BufferType.DRAM)
    dtype_16 = ttl.tensor.DataType.BFLOAT16
    dtype_8 = ttl.tensor.DataType.BFLOAT8_B

    A = torch.randn(a_shape)
    B = torch.randn(b_slice_shape) - 0.95

    a_t = ttl.tensor.Tensor(A, dtype_16).to(ttl.tensor.Layout.TILE).to(device, mem_config)
    b_t_slice = ttl.tensor.Tensor(B, dtype_8).to(ttl.tensor.Layout.TILE).to(device, mem_config)

    compute_kernel_config = ttl.tensor.WormholeComputeKernelConfig(
        math_fidelity=ttl.tensor.MathFidelity.LoFi,
        math_approx_mode=True,
        fp32_dest_acc_en=False,
        packer_l1_acc=True,
    )

    program_config = ttl.operations.primary.MatmulMultiCoreReuseMultiCast1DProgramConfig(
        compute_with_storage_grid_size=(8, 8),
        in0_block_w=1,
        out_subblock_h=1,
        out_subblock_w=1,
        per_core_M=64,
        per_core_N=8,
        fuse_batch=True,
        fused_activation=None,
        mcast_in0=True,
    )

    out = ttl.operations.primary.matmul_1d(
        a_t,
        b_t_slice,
        program_config=program_config,
        output_mem_config=mem_config,
        output_dtype=dtype_16,
        compute_kernel_config=compute_kernel_config
    )

```

**Additional context**
- Removing l1 accumulate or switching dimensions passes. I used DPRINT to figure out what happens with the compute kernel ant it seems to hang on block 128 on the following line: https://github.com/tenstorrent-metal/tt-metal/blob/main/tt_eager/tt_dnn/op_library/bmm/kernels/compute/bmm_large_block_zm_fused_bias_activation.cpp#L207
- This is not blocking me at the moment, I just discovered it when I was trying out some matmuls.

**Comment by jliangTT** [comment] 2024-03-31 00:08
this is P2 - please schedule accordingly. though it is @yugaoTT who recently enable some L1 accumulation. Let me know if this is in your queue.

**Comment by yugaoTT** [comment] 2024-04-03 14:31
I'm able to repro on a 2 core test, it seems like a syncing issue. When using unpacker to dprint out sth during run, the hangs stops, indicating unpacker is having some timing issues.

**Comment by yugaoTT** [comment] 2024-04-03 14:36
watcher indicates unpacker hangs before calling `wait_for_next_context(2);` @rtawfik01 could this be the syncing issue between unpacker and math?

**Comment by rtawfik01** [comment] 2024-04-08 20:06
@yugaoTT yes it could be, I ran some more experiments. This is what I see:
1. It hangs at 500Mhz, 800Mhz & 1000Mhz AICLK, so its probably not di/dt related.
2. It consistently hangs in the iteration with num_blocks = 127 & in0_sublock = 31, and it deterministically hangs in that iter.
3. When the board is at 1000Mhz, adding extra nops/dprints causes the test to pass, which shows its a timing issue that needs extra cycles injected. 

I'm still investigating, and I will update once I find the root cause.

**Comment by rtawfik01** [comment] 2024-04-10 21:31
Hi @s-jovic can you try this fix? https://github.com/tenstorrent-metal/tt-metal/commit/792d782f5cb6e5a905e5f5741cbd4c4347e3fbec

The issue is that there are missing cb wait fronts for pack l1 accumulation, and when it reaches k=128 in this test, it reaches the cb fifo limit (2^16) before the rd and wr ptrs are wrapped around to 0 again, and it produces incorrect values without the cb_wait_front.

Please let me know if it works, I tried it with your `test_reproduce_l1_acc_hang` test and it no longer hangs on my machine

**Comment by s-jovic** [comment] 2024-04-11 09:07
Hey @rtawfik01, works for me as well!

**Comment by rtawfik01** [comment] 2024-04-11 18:12
Pushed the fix here: https://github.com/tenstorrent-metal/tt-metal/pull/7335

**Closed by rtawfik01** 2024-04-11 18:12 UTC
Labels: bug, P2_should_have, op_cat: mm
