### ISSUE TITLE
Python Op infra for sliding window ops - maxpool, conv, untilize_with_halo

### ISSUE THREAD

**Issue by tt-nshanker** [tenstorrent-metal/tt-metal#3933] opened 2023-11-21 19:08 UTC
Op classes in python which have functions to construct config sharded l1 tensor, weights/bias tensors and get stats for l1 buffers.
Implements config caching on host for unique op params.
![image](https://github.com/tenstorrent-metal/tt-metal/assets/109384087/cfe73794-f8aa-4f68-909c-b10e4f8cc742)

**Comment by TT-BrianLiu** [comment] 2023-12-12 23:24
Duplicate of #3796.

**Closed by TT-BrianLiu** 2023-12-12 23:24 UTC
Labels: ResNet-50
