### ISSUE TITLE
SD TTNN: TtResnetBlock2D

### ISSUE THREAD

**Issue by boris-drazic** [tenstorrent-metal/tt-metal#4793] opened 2024-01-18 15:26 UTC
Implement subgraph `TtResnetBlock2D` and make two tests: one for 256x256 image size and one for 512x512 image size.
Have one test file named something like `test_resnet_block_2d.py` and inside it two tests `test_resnet_block_2d_256x256` and `test_resnet_block_2d_512x512`. Tests should be parametrized with following input shapes:

- [x] Shape 1:  **256x256**
    - [x] input case 1: [2, 320, 32, 32]
    - [x] input case 2: [2, 320, 16, 16]
    - [x] input case 3: [2, 640, 16, 16]
    - [x] input case 4: [2, 640, 8, 8]
    - [x] input case 5: [2, 1280, 8, 8]
    - [x] input case 6: [2, 1280, 4, 4]
    - [x] input case 7: [2, 2560, 4, 4]
    - [x] input case 8: [2, 2560, 8, 8]
    - [x] input case 9: [2, 1920, 8, 8]
    - [x] input case 10: [2, 1920, 16, 16]
    - [x] input case 11: [2, 1280, 16, 16]
    - [x] input case 12: [2, 960, 16, 16]
    - [x] input case 13: [2, 960, 32, 32]
    - [x] input case 14: [2, 640, 32, 32]

- [x] Shape 2:  **512x512**
    - [x] input case 1: [2, 320, 64, 64]
    - [x] input case 2: [2, 320, 32, 32]
    - [x] input case 3: [2, 640, 32, 32]
    - [x] input case 4: [2, 640, 16, 16]
    - [x] input case 5: [2, 1280, 16, 16]
    - [x] input case 6: [2, 1280, 8, 8]
    - [x] input case 7: [2, 2560, 8, 8]
    - [x] input case 8: [2, 2560, 16, 16]
    - [x] input case 9: [2, 1920, 16, 16]
    - [x] input case 10: [2, 1920, 32, 32]
    - [x] input case 11: [2, 1280, 32, 32]
    - [x] input case 12: [2, 960, 32, 32]
    - [x] input case 13: [2, 960, 64, 64]
    - [x] input case 14: [2, 640, 64, 64]

For all the 28 cases, mentioned above:
- temb: [1, 1, 2, 1280]

**Comment by punithsekar** [comment] 2024-01-23 13:09
While implementing the ttn_resnetBlock, we encountered the following issues. 
The problem arises from the weights shape of conv2d(parameters.mid_block.resnets[0].conv1), where the shape are 1280, 1280, 3, 3. The issue arises during the attempt to place weights on the device after converting them into a ttnn tensor with a row_major layout. The encountered error is as follows:

```
>       return Tensor(ttl_tensor.to(device, memory_config))
E       RuntimeError: TT_FATAL @ tt_metal/impl/buffers/buffer.cpp:30: page_size % sizeof(uint32_t) == 0
E       info:
E       Page size must be divisible by sizeof(uint32_t) because buffers hold uint32_t values
E       backtrace:
E        --- tt::tt_metal::Buffer::Buffer(tt::tt_metal::Device*, unsigned long, unsigned long, tt::tt_metal::BufferType, tt::tt_metal::TensorMemoryLayout, std::optional<tt::tt_metal::ShardSpecBuffer>)

```
As a workaround, we proceeded by retaining the conv2D weights on the host. However, we encountered another issue while calling the initialized conv1 function:

```
conv1=ttnn.Conv2D(in_channels,out_channels,weight=parameters.conv1.weight,bias=parameters.conv1.bias,kernel_size=3,stride=1,padding=1,device=device,input_height=8,input_width=8,use_1d_systolic_array=False,batch_size=2,reader_patterns_cache={})
hidden_states=conv1(hidden_states)

ttnn/conv.py:108: in __call__
    return ttnn.Tensor(self.conv(activation.value))
tt_eager/tt_dnn/op_library/sliding_window_op_infra/tt_py_composite_conv.py:651: in __call__
    return self.conv(activation)
tt_eager/tt_dnn/op_library/sliding_window_op_infra/tt_py_composite_conv.py:633: in composite_conv
    utwh_output = self.tt_py_untilize_with_halo_op(activation)
tt_eager/tt_dnn/op_library/sliding_window_op_infra/tt_py_untilize_with_halo.py:270: in __call__
    return self.utwh(activation)

activation = <tt_lib.tensor.Tensor object at 0x7fbf60d17ef0>

    def utwh_(activation):
        # print("sliding_window_op_params=", self.sliding_window_op_params)
>       return ttl.tensor.untilize_with_halo_v2(
            activation,
            utwh_kernel_configs["local_pad_tensor"],
            utwh_kernel_configs["ll_data_tensor"],
            utwh_kernel_configs["l_data_tensor"],
            utwh_kernel_configs["local_data_tensor"],
            utwh_kernel_configs["r_data_tensor"],
            utwh_kernel_configs["rr_data_tensor"],
            pad_val,
            self.sliding_window_op_params.num_cores_nhw,
            utwh_kernel_configs["max_out_nsticks_per_core"],
            utwh_kernel_configs["local_pad_nsegments_per_core"],
            utwh_kernel_configs["ll_data_nsegments_per_core"],
            utwh_kernel_configs["l_data_nsegments_per_core"],
            utwh_kernel_configs["local_data_nsegments_per_core"],
            utwh_kernel_configs["r_data_nsegments_per_core"],
            utwh_kernel_configs["rr_data_nsegments_per_core"],
            utwh_kernel_configs["local_data_src_start_offsets_per_core"],
            utwh_kernel_configs["ll_data_src_start_offsets_per_core"],
            utwh_kernel_configs["l_data_src_start_offsets_per_core"],
            utwh_kernel_configs["r_data_src_start_offsets_per_core"],
            utwh_kernel_configs["rr_data_src_start_offsets_per_core"],
            out_mem_config,
        )
E       RuntimeError: TT_ASSERT @ tt_eager/tt_dnn/op_library/untilize/untilize_with_halo_op_v2.cpp:637: input_tensor.memory_config().is_sharded()
E       backtrace:
```

**Comment by punithsekar** [comment] 2024-01-24 15:09
We replaced the usage of output=hidden_states+temb with tt_lib.tensor.bcast.
An issue arises with the temb tensor, as it is not on the device. This occurs because the temb tensor is moved to the host during the permutation operation (Because the temb shape becomes [2,1280,1,1] after permutation) .
```
            input_tensor_b = ttnn.unsqueeze_to_4D(input_tensor_b)
            ttl_input_tensor_b = input_tensor_b.value
            if ttl_input_tensor_b.storage_type() != ttl.tensor.StorageType.DEVICE:
>               raise RuntimeError("input_tensor_a must be on device!")
E               RuntimeError: input_tensor_a must be on device!
```

The error can be reproduced using the following code snippet:

```
def test_add(device):
    hidden_states=torch.randn(2,1280,8,8)
    temb=torch.randn(1,1,2,1280)
    hidden_states = ttnn.from_torch(hidden_states, layout=ttnn.TILE_LAYOUT, device=device, dtype=ttnn.bfloat16)
    temb = ttnn.from_torch(temb, layout=ttnn.ROW_MAJOR_LAYOUT, device=device, dtype=ttnn.bfloat16)
    temb=ttnn.permute(temb,(2,3,0,1))
    output=ttnn.add(hidden_states,temb)
```

**Comment by boris-drazic** [comment] 2024-01-24 15:17
@punithsekar can you file a bug for this to project `ttnn-Team Global Dashboard`?

**Comment by saichandax** [comment] 2024-01-25 05:12
Issue created at #4899 for ttnn.add

**Comment by punithsekar** [comment] 2024-02-02 13:33
ResnetBlock2D sub-module has been implemented along with two tests: one for an image size of 256x256 and another for an image size of 512x512.
All the test cases are passing, Working on using ttnn.Conv2D instead of fallback_ops for conv.

Corresponding PR #5084 

While working on using ttnn.Conv2D,
We encounter issue while keeping filter_h,filter_w=1 and pad_h,pad_w=0 for conv2d as Resnet block uses the following configurations.

Created issue on it #5094

**Comment by saichandax** [comment] 2024-02-06 13:44
PR is merged, closing the ticket.

**Closed by saichandax** 2024-02-06 13:44 UTC
Labels: models, feature
