### ISSUE TITLE
Indexed slicing for read+write ops for MoE

### ISSUE THREAD

**Issue by yieldthought** [tenstorrent-metal/tt-metal#5909] opened 2024-03-01 15:51 UTC
To match the torch behaviour.
Indexed slicing (for read and write operations)
(32, 1) -> (?, 1) / (32, 4096) -> (?, 4096) / (?, 4096) -> (32, 4096)

Context for Mixtral (internal only): https://tenstorrent.sharepoint.com/:p:/s/Jasmina/EUZv5VSt7IBKj5cI05eBSOsBeVSAt9S_k3B6FCfzyT5RdQ?e=zkg8rF 

Open to better ideas for how to map the MoE branching operation than the torch approach, but this is our opening suggestion.

**Comment by yieldthought** [comment] 2024-03-08 14:52
We have brought up functional Mixtral 8x7b on T3000 on schedule and next Friday is our target for delivering optimal performance.

This op is the only missing dependency that's _forcing_ us to keep going back to the host (in the worst case we can emulate top-k for k=2 with repeated argmax calls). Can I get an estimate of the chances of getting this in the next 2-3 days so I can update our milestone risk?

**Comment by tarafdarTT** [comment] 2024-03-08 20:55
@yieldthought, wanted to clarify on what indexed slicing is.

is it a normal PyTorch slice? (input is start and end of a tensor). I had a bit of trouble understanding the example.

If it's a normal PyTorch slice, we should have that right now (it's called unpad in our codebase).

**Comment by SeanNijjar** [comment] 2024-03-08 21:43
Hey @tarafdarTT, it's more like the latter. Checkout the bottom of the diagram on the third slide. What's happening is there is a dense tensor of rows on each chip. There is a (I think a separate) index tensor which describes the mappings of the rows in the dense tensor into a larger tensor (the mentioned zero-filled tensor). So for example, you see the left side is indexing/filling into rows 0, 1, 4, with its 3 row tensor and the right is indexing into 2,3 with its 2 row tensor.

<img width="678" alt="image" src="https://github.com/tenstorrent-metal/tt-metal/assets/1865303/ed9e8907-6eb4-430e-bf48-dec8c68b7dd3">

So I'd say from a data access pattern perspective, it's almost like a reverse embedding (write from dense to large tensor rather then read from large tensor to dense).

**Comment by tarafdarTT** [comment] 2024-03-11 16:28
@sraizada-tt @SeanNijjar @yieldthought 
I think we can compose this of ops we already do have implemented.
We have the slice op (called unpad ) and concat op working.

So this should be:
```
sliced_index(input, input_slice_to_write, batch_id) = concat ( concat( unpad(input, 0 to batch_id - 1) , input_slice_to_write), unpad(input, batch_id + 1 to input_size) ) 
```

**Comment by sraizada-tt** [comment] 2024-03-11 16:39
^ will need 2*b unpads , concats

**Comment by tarafdarTT** [comment] 2024-03-13 11:14
Addressed in PR: 
https://github.com/tenstorrent-metal/tt-metal/pull/6328

**Closed by tarafdarTT** 2024-03-13 11:14 UTC
Labels: P1_feature_needed, feature, op_cat: perf TMs, mixtral, LLM_feature, LLMs on Metal

**Comment by SeanNijjar** [comment] 2024-03-19 17:10
Pulling in from offline discussion:
> I spoke with Mark and Stuti this morning and my takeaway was that they'll be able to deal with this limitation of not having dynamic output shapes. They've restructured this part of the model to not need them and it sounds like there isn't really going to be a perf penalty until/unless they decide they want to really bump up batch (128 or more)

Although the issue is already closed, the Mixtral bringup team has designed around this original ask (namely, the desire for dynamic output shapes.
