### ISSUE TITLE
Add CI for model functionality/perf on wormhole

### ISSUE THREAD

**Issue by skhorasganiTT** [tenstorrent-metal/tt-metal#5380] opened 2024-02-14 16:21 UTC
Tracking issue for adding CI to test model functionality/perf on wormhole. Currently, model tests are run on grayskull; this CI would help reduce regressions on wormhole as additional models are added or existing ones are modified.

**Comment by tapspatel** [comment] 2024-02-14 16:50
@rayraykay Couple of questions,

1. are we provisioning a currently allocated machines into wormhole perf CI? What are the current resource count for wormhole ci/dev machines in cloud. Do we need to ask for another wormhole machine.
2. for perf, I'm assuming this will be setup as a bare metal machine. Is this so? Or will it be virtual. 
3. will we mirror gray skull perf ci, ie will this tests run on post-commit, or model pipeline. From the request, it sounds like they want to add models that test perf. 
4. is this the workflow we modify: https://github.com/tenstorrent-metal/tt-metal/blob/main/.github/workflows/perf-models.yaml
5. In run_tests.sh, I see the following

`elif [[ $pipeline_type == "models_performance_bare_metal" || $pipeline_type == "models_device_performance_bare_metal" ]]; then
        run_models_performance_bare_metal_pipeline_tests "$tt_arch" "$pipeline_type" "$dispatch_mode"
    elif [[ $pipeline_type == "models_performance_virtual_machine" ]]; then
        run_models_performance_virtual_machine_pipeline_tests "$tt_arch" "$pipeline_type"`

Is this the location where ticket requester will define their models

**Comment by tapspatel** [comment] 2024-02-14 16:56
@skhorasganiTT Will the models team need access to a cache for model weights/other files? This should be taken into account for the request and triage what infra already exists for this.

**Comment by tt-rkim** [comment] 2024-02-14 18:00
Hey everyone, will respond to your questions soon, delayed because I'm out today.

Please do not tag @rayraykay - tag @tt-rkim instead. The first one is my personal account that I do not use for tenstorrent work.

**Comment by skhorasganiTT** [comment] 2024-02-14 18:16
Hey @tapspatel, the request is to replicate whatever infra already exists for grayskull to wormhole. I am not sure whether a cache is currently used, but that would likely be useful to avoid large downloads.

**Comment by tapspatel** [comment] 2024-02-27 22:58
@tt-rkim do you have any info on this? Is there an already provisioned runner for WH perf in CI

**Comment by uaydonat** [comment] 2024-03-08 20:20
Just re-iterating that we need WH CI for perf tests running nightly. We brought up 4-5 different models on WH, these need to be tested on daily basis to avoid regressions.

**Comment by TT-billteng** [comment] 2024-03-13 15:30
closing this, see comment above

**Closed by TT-billteng** 2024-03-13 15:30 UTC
Labels: infra-ci, P0_Showstopper, feature, LLM_feature
